---
title: "Getting started with R"
output: html_notebook
---

This notebook contains the second part of Task1 Find the errors in a R script.

This notebook is intended to learn the basics of R.

```{r - Initial imports}
#install.packages("readr")

library("readr")

IrisDataset <- read.csv("iris.csv")

attributes(IrisDataset)
```

```{r}
summary(IrisDataset)

str(IrisDataset)

names(IrisDataset)
```
```{r}
#hist(IrisDataset$Species)
#Unable to plot histogram of vector of strings in R. Either factorize:
plot( as.factor( IrisDataset$Species )) 
#Or use other libs such as ggplot2:
library("ggplot2")
qplot( IrisDataset$Species ) 

#Or this was a mistake and it is pretended a histogram of any other variable:
hist( IrisDataset$Sepal.Length)
hist( IrisDataset$Sepal.Width)
hist( IrisDataset$Petal.Length)
hist( IrisDataset$Petal.Width)

```
```{r}
#Added closing parenthesis as well as plotting for other variables.
plot( IrisDataset$Sepal.Length)
plot( IrisDataset$Sepal.Width)
plot( IrisDataset$Petal.Length)
plot( IrisDataset$Petal.Width)

plot( IrisDataset$Petal.Length, IrisDataset$Petal.Width)
```
```{r}
#Unable to plot whole dataset as there are non numerical features. Instead plot variable by variable.
qqnorm( IrisDataset$Sepal.Length)
qqnorm( IrisDataset$Sepal.Width)
qqnorm( IrisDataset$Petal.Length)
qqnorm( IrisDataset$Petal.Width)

```
```{r}
#Cannot convert characters into numeric, convert into factor.
IrisDataset$Species <- as.factor(IrisDataset$Species)
#If numeric is required then an additional step would be required:
#IrisDataset$Species<- as.numeric( as.factor(IrisDataset$Species))
```

```{r}
set.seed(123)
trainSize <- round(nrow(IrisDataset) * 0.7) #Train size was too small
testSize <- nrow(IrisDataset) - trainSize #trainsize instead of trainset
trainSize
testSize
```
```{r}
#Missing random sample of train indices
training_indices<-sample(seq_len(nrow(IrisDataset)),size =trainSize) # Select random sample of row numbers with size 'trainsize'

trainSet <- IrisDataset[training_indices, ]

testSet <- IrisDataset[-training_indices, ]

#No need to repeat this part
#set.seed(405)
#trainSet <- IrisDataset[training_indices, ]
#testSet <- IrisDataset[-training_indices, ]
```

```{r}
#Write trainSet in the data parameter instead of on each variable just to improve readability
LinearModel<- lm(Petal.Length ~ Petal.Width, trainSet) #The analysis goal is to predict a petal's length using the petal’s width.
summary(LinearModel)
```

```{r}
#Variable mispelled
prediction<-predict(LinearModel,testSet)

prediction
```
```{r}
cbind(Pred_length = prediction, Real_length = testSet$Petal.Length)
write.csv(data.frame(cbind(Pred_length = prediction, Real_length = testSet$Petal.Length)), file="sad.tab", row.names=TRUE)
```

